### ISSUE TITLE
 asymmetric data PSI

### ISSUE THREAD

**Issue by reclock** [osu-crypto/libPSI#19]
Does the kkrt protocol support asymmetric data PSI?

**Comment by reclock** [comment]
this my run command
./frontend.exe -r 0 -n 1000 -t 1 -v 1 -kkrt -b 256
./frontend.exe -r １ -n 10000 -t 1 -v 1 -kkrt -b 256

**Comment by ladnir** [comment]
It does. 

https://github.com/osu-crypto/libPSI/blob/4712d8ffaf6a7759bfb10025290c59ecee60bbad/libPSI/PSI/Kkrt/KkrtPsiSender.h#L33

The command line thing just doesn't support it.

**Comment by reclock** [comment]
Which routine in the current project can perform the test。

 void init(u64 senderSize, u64 recverSize, u64 statSecParam, span<Channel> chls, NcoOtExtSender& otSender, block seed);

libPSI/frontend/fileBasedPSI.cpp     this  can support it? thanks

**Comment by reclock** [comment]
I have tested successfully, thank you
