### ISSUE TITLE
I can't solve this problem

### ISSUE THREAD

**Issue by HuJinguang** [osu-crypto/libPSI#2]
frontend/CMakeFiles/frontend.exe.dir/build.make:364: recipe for target 'bin/frontend.exe' failed
make[2]: *** [bin/frontend.exe] Error 1
CMakeFiles/Makefile2:196: recipe for target 'frontend/CMakeFiles/frontend.exe.dir/all' failed
make[1]: *** [frontend/CMakeFiles/frontend.exe.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ladnir** [comment]
Please give the full error.

**Comment by HuJinguang** [comment]
[ 99%] Linking CXX executable ../bin/frontend_libOTe
/usr/bin/ld: ../lib/libSimplestOT.a(fe25519_freeze.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(fe25519_mul.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(fe25519_square.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge25519_add_p1p1.s.o): relocation R_X86_64_32S against symbol `CONST_2P0' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge25519_dbl_p1p1.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge25519_lookup_niels.s.o): relocation R_X86_64_32S against symbol `CONST_2P0' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge25519_nielsadd2.s.o): relocation R_X86_64_32S against symbol `CONST_2P0' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge25519_p1p1_to_p2.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge25519_p1p1_to_p3.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge4x_add_p1p1.s.o): relocation R_X86_64_32S against symbol `Gk' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge4x_double_p1p1.s.o): relocation R_X86_64_32S against symbol `scale19' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge4x_lookup.s.o): relocation R_X86_64_32S against symbol `_allone' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge4x_lookup_niels.s.o): relocation R_X86_64_32S against symbol `_allone' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(ge4x_niels_add_p1p1.s.o): relocation R_X86_64_32S against symbol `scale19' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(gfe4x_mul.s.o): relocation R_X86_64_32S against symbol `scale19' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(gfe4x_square.s.o): relocation R_X86_64_32S against symbol `scale19' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(fe25519_nsquare.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
frontend/CMakeFiles/frontend_libOTe.dir/build.make:130: recipe for target 'bin/frontend_libOTe' failed
make[2]: *** [bin/frontend_libOTe] Error 1
CMakeFiles/Makefile2:480: recipe for target 'frontend/CMakeFiles/frontend_libOTe.dir/all' failed
make[1]: *** [frontend/CMakeFiles/frontend_libOTe.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ladnir** [comment]
Can you please post what the following outputs:

make clean
make VERBOSE=true

**Comment by HuJinguang** [comment]
[err.txt](https://github.com/osu-crypto/libPSI/files/2930070/err.txt)

**Comment by ladnir** [comment]
sorry, forgot about this. See the link for a fix, basically you can add `-no-pie` to the CXX flags. Or turn off the assembly based simplestOT.

https://github.com/osu-crypto/libOTe/issues/18

**Comment by nianer** [comment]
> Or turn off the assembly based simplestOT.
How to turn off the assembly based simplestOT?

**Comment by nianer** [comment]
Thanks for your reply !
