### ISSUE TITLE
Is it possible to achieve the conversion between string  and  block 

### ISSUE THREAD

**Issue by L-coder148** [osu-crypto/libPSI#20]
Is it possible to achieve the conversion between `String` and `block `, the string might be a meaningful sentence like "I am Alice" or "yes".

**Comment by ladnir** [comment]
Hash the string to a block. RandomOracle can do this.

**Comment by L-coder148** [comment]
Thanks for your early reply，I want to send the vector `ss` ，but there was an error. I saw the function in` Channel.h`, but I still can not deal with it.
```
        std::vector<std::string> ss(2);
        ss.push_back("I am Alice");
        ss.push_back("I am Alice");

        auto routine = [&](u64 t)
        {
            chl0.asyncSend(ss);
        };
```
![image](https://user-images.githubusercontent.com/75669641/127487415-697de18b-03fc-4cdb-9d58-89dd8f913ea1.png)

**Comment by ladnir** [comment]
Channel can only send vector of basic data types. Basically if you can use memcpy.  string is not a basic data type. 

Join all your strings and send one big string.
