### ISSUE TITLE
Execute bash build.sh to report an error

### ISSUE THREAD

**Issue by sunyinggang** [osu-crypto/libPSI#24]
-- Relic_LIB:  /home/psi/Documents/psi/libOTe/out/install/linux/lib/librelic_s.a
-- Relic_inc:  /home/psi/Documents/psi/libOTe/out/install/linux/include

-- SODIUM_INCLUDE_DIRS:  /home/psi/Documents/psi/libOTe/out/install/linux/include
-- SODIUM_LIBRARIES:  /home/psi/Documents/psi/libOTe/out/install/linux/lib/libsodium.a
-- SODIUM_MONTGOMERY:  ON

-- Could NOT find Boost: missing: thread (found /home/psi/Documents/psi/libOTe/out/install/linux/lib/cmake/Boost-1.77.0/BoostConfig.cmake (found suitable version "1.77.0", minimum required is "1.77.0"))
CMake Error at /home/psi/Documents/psi/libOTe/out/build/linux/cryptoTools/cryptoToolsDepHelper.cmake:223 (message):
  Failed to find boost 1.77.  Add -DFETCH_BOOST=ON or -DFETCH_ALL=ON to auto
  download.
Call Stack (most recent call first):
  /home/psi/Documents/psi/libOTe/out/build/linux/cryptoTools/cryptoToolsConfig.cmake:22 (include)
  /home/psi/Documents/psi/libOTe/out/build/linux/libOTeConfig.cmake:27 (find_package)
  /home/psi/Documents/psi/libOTe/cmake/libOTeConfig.cmake:20 (include)
  CMakeLists.txt:65 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/psi/Documents/psi/libPSI/out/build/linux/CMakeFiles/CMakeOutput.log".
See also "/home/psi/Documents/psi/libPSI/out/build/linux/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

**Comment by ladnir** [comment]
is this with `python build.py` ?
