### ISSUE TITLE
The problem of multi-thread

### ISSUE THREAD

**Issue by changjian4556** [osu-crypto/libPSI#3]
At Rr16, we output the intersection in AknMbfReceiver.cpp, and found that the intersection are correct when running the code using a single thread. But the intersection are wrong when running the code using multi-thread. Did we run it wrong?

**Comment by ladnir** [comment]
You probably did not do anything wrong. I have not been maintaining the multi-threaded code.

Is there are a strong reason to fix it?

**Comment by changjian4556** [comment]
&nbsp;I&nbsp;‘m&nbsp;sorry&nbsp;to&nbsp;trouble&nbsp;you.&nbsp;you&nbsp;mean&nbsp;there&nbsp;is&nbsp;no&nbsp;need&nbsp;to&nbsp;fix&nbsp;it.&nbsp;But&nbsp;you&nbsp;measured&nbsp;the&nbsp;time&nbsp;when&nbsp;using&nbsp;multi-threaded&nbsp;in&nbsp;&nbsp;paper&nbsp;Improved&nbsp;Private&nbsp;Set&nbsp;Intersection&nbsp;against&nbsp;Malicious&nbsp;Adversaries.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Peter Rindal"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月11日(星期五) 中午12:54
收件人:&nbsp;"osu-crypto/libPSI"<libPSI@noreply.github.com&gt;;
抄送:&nbsp;"常键"<2958197163@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [osu-crypto/libPSI] The problem of multi-thread (#3)




You probably did not do anything wrong. I have not been maintaining the multi-threaded code.
 
Is there are a strong reason to fix it?

**Comment by ladnir** [comment]
What? Please respond on the website.

**Comment by ladnir** [comment]
If you are trying to benchmark for performance numbers, it's probably safe to ignore the issue.. I think it's just that the two threads are writing the output set over one another...

**Comment by changjian4556** [comment]
Thanks for your reply.
