### ISSUE TITLE
Question about correctness 

### ISSUE THREAD

**Issue by TY-cc** [osu-crypto/libPSI#30]
i created two .csv as input of psi.
The contents of  one csv is  1 to 1048576, another  contents is 800001 to  (1048576+800000).
but the result is not the last 200000 items of  1 to 1048576.  why?

i am not good at English , sorry. But i hope you can understand  my means.

**Comment by ladnir** [comment]
I'll take a look

**Comment by ladnir** [comment]
the result of the PSI is the index of the intersection. Let `I` be the output file and `R` be the receiver's set, then you can get the actual intersection as `{ r_i \in R | i \in I}`

**Comment by TY-cc** [comment]
thanks, i'll try
