### ISSUE TITLE
I also meet the problem as changjian4556

### ISSUE THREAD

**Issue by freelyyu** [osu-crypto/libPSI#4]

**Comment by ladnir** [comment]
then comment there.. ;)

**Comment by freelyyu** [comment]
Dear sir



     At Rr16, we output the intersection in AknMbfReceiver.cpp, and found that the intersection are correct when running the code using a single thread. But the intersection are wrong when running the code using multi-thread. But  Peter Rindal comments  that he have not been maintaining the multi-threaded code. there is no need to fix it. But he measured the time in  paper Improved Private Set Intersection against Malicious Adversaries.






------------------ 原始邮件 ------------------
发件人: "Jack Doerner"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 中午12:59
收件人: "osu-crypto/libPSI"<libPSI@noreply.github.com>;
抄送: "freely钰"<482356841@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [osu-crypto/libPSI] I also meet the problem as changjian4556 (#4)




then comment there.. ;)
