### ISSUE TITLE
volepsi how to use it to run a demo?

### ISSUE THREAD

**Issue by nihaoqingtuan** [osu-crypto/libPSI#44]
May I ask what command volepsi uses to start it under what file?

**Comment by nihaoqingtuan** [comment]
Here's what I've come up with after trying



$ ./frontend -kkrt -r 0
 0 - Paxos_buildRow_Test           Passed   0ms
 1 - Paxos_solve_Test              Passed   26ms
 2 - Paxos_solve_u8_Test           Passed   11ms
 3 - Paxos_solve_mtx_Test          Passed   17ms
 4 - Paxos_invE_Test               Passed   0ms
 5 - Paxos_invE_g3_Test            Passed   0ms
 6 - Paxos_solve_gap_Test          Passed   2ms
 7 - Paxos_solve_rand_Test         Passed   0ms
 8 - Paxos_solve_rand_gap_Test     Passed   3ms
 9 - Baxos_solve_Test              Passed   0ms
10 - Baxos_solve_mtx_Test          Passed   0ms
11 - Baxos_solve_par_Test          Passed   22ms
12 - Baxos_solve_rand_Test         Passed   35ms
13 - SilentTripleGen_test          Passed   3ms
14 - generateBase_test             Passed   45ms
15 - isZeroCircuit_Test            Passed   0ms
16 - Gmw_half_test                 Passed   0ms
17 - Gmw_basic_test                Passed   0ms
18 - Gmw_inOut_test                Passed   0ms
19 - Gmw_xor_test                  Passed   0ms
20 - Gmw_and_test                  Passed   47ms
21 - Gmw_or_test                   Passed   47ms
22 - Gmw_na_and_test               Passed   46ms
23 - Gmw_xor_and_test              Passed   46ms
24 - Gmw_aa_na_and_test            Passed   48ms
25 - Gmw_noLevelize_test           Passed   48ms
26 - Gmw_add_test                  Passed   47ms
27 - RsOprf_eval_test              Passed   51ms
28 - RsOprf_mal_test               Passed   47ms
29 - RsOpprf_eval_blk_test         Passed   52ms
30 - RsOpprf_eval_u8_test          Passed   52ms
31 - RsOpprf_eval_blk_mtx_test     Passed   50ms
32 - RsOpprf_eval_u8_mtx_test      Passed   48ms
33 - Psi_Rs_empty_test             Passed   48ms
34 - Psi_Rs_partial_test           Passed   51ms
35 - Psi_Rs_full_test              Passed   51ms
36 - Psi_Rs_multiThrd_test         Passed   53ms
37 - Psi_Rs_mal_test               Passed   52ms
38 - Cpsi_Rs_empty_test            Passed   548ms
39 - Cpsi_Rs_partial_test          Passed   103ms
40 - Cpsi_Rs_full_test             Passed   520ms
41 - Cpsi_Rs_full_add32_test       Passed   0ms

=============================================                                                                                
            All Passed (42)                                                                                                  
=============================================                                                                                
WARNING: This program made use of the LPN silver encoder. This encoder is experimental and should not be used in production. Rebuild libOTe with `-DNO_SILVER_WARNING=TRUE` to disable this message or build the library with `-DENABLE_BITPOLYMUL=TRUE` to use an encoding with provable minimum distance. /home/10336999@zte.intra/PSI/volepsi/thirdparty/libOTe/libOTe/TwoChooseOne/Silent/SilentOtExtSender.cpp:60

**Comment by ladnir** [comment]
you can also open an issue for volepsi on the volepsi repo...

Here is the main file https://github.com/Visa-Research/volepsi/blob/main/frontend/main.cpp#L146

There is an example on how to run the protocol with manual message passing. I'm in the process of added a TLS example. Almost done.

**Comment by nihaoqingtuan** [comment]
i know that.but in volepsi repo ,No one seems to answer the question.so i have to ask you. thanks, have a good day. I have to sleep.There is time difference between us.



---- Replied Message ----
| From | Peter ***@***.***> |
| Date | 10/27/2022 00:32 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [osu-crypto/libPSI] volepsi how to use it to run a demo? (Issue #44) |

you can also open an issue for volepsi on the volepsi repo...

Here is the main file https://github.com/Visa-Research/volepsi/blob/main/frontend/main.cpp#L146

There is an example on how to run the protocol with manual message passing. I'm in the process of added a TLS example. Almost done.

**Comment by nihaoqingtuan** [comment]
it's ok.I'll run the volepsi demo tomorrow. Goodnight.



---- Replied Message ----
| From | Peter ***@***.***> |
| Date | 10/27/2022 01:05 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [osu-crypto/libPSI] volepsi how to use it to run a demo? (Issue #44) |

oh, ha, I'm also the one who monitors that repo. Just missed the issue you opened.

**Comment by nihaoqingtuan** [comment]
ok.i just open issue in volepsi repo about how to run it.



---- Replied Message ----
| From | Peter ***@***.***> |
| Date | 10/27/2022 01:05 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [osu-crypto/libPSI] volepsi how to use it to run a demo? (Issue #44) |

oh, ha, I'm also the one who monitors that repo. Just missed the issue you opened.
