### ISSUE TITLE
Why do I run a 50 million row data set, and the following error is reported.

### ISSUE THREAD

**Issue by didadida321** [osu-crypto/libPSI#47]
l use ./frontend.exe -kkrt to run a 50 million row data set.
But it shows error:
network receive error._autoName_0 ): End of file at  libPSI/thirdparty/libOTe/cryptoTools/cryptoTools/Network/Channel.cpp:819
terminate called after throwing an instance of 'std::runtime_error' what():  End of file

**Comment by ladnir** [comment]
maybe the other party is crashing (out of memory?) and this is causing the socket to close (End of file).
