### ISSUE TITLE
Conversion Error

### ISSUE THREAD

**Issue by maplepicker** [osu-crypto/libPSI#51]
System: Windows10
IDE: Visual Studio 2022
Problem: When I try to compile the project, following problems show up, and I'm confused that mOtSender->recvCorrection method takes a **Channel** as input, while its definition is **Socket**.

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'macoro::task<void,true> osuCrypto::NcoOtExtSender::recvCorrection(osuCrypto::Socket &,osuCrypto::u64)': cannot convert argument 1 from 'T' to 'osuCrypto::Socket &'	libPSI	C:\Users\ceezous\Desktop\libPSI-private\libPSI\PSI\Kkrt\KkrtPsiSender.cpp	374	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'macoro::task<void,true> osuCrypto::NcoOtExtSender::init(osuCrypto::u64,osuCrypto::PRNG &,osuCrypto::Socket &)': cannot convert argument 3 from 'T' to 'osuCrypto::Socket &'	libPSI	C:\Users\ceezous\Desktop\libPSI-private\libPSI\PSI\Kkrt\KkrtPsiSender.cpp	86	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'macoro::task<void,true> osuCrypto::NcoOtExtReceiver::sendCorrection(osuCrypto::Socket &,osuCrypto::u64)': cannot convert argument 1 from 'T' to 'osuCrypto::Socket &'	libPSI	C:\Users\ceezous\Desktop\libPSI-private\libPSI\PSI\Kkrt\KkrtPsiReceiver.cpp	189	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'macoro::task<void,true> osuCrypto::NcoOtExtReceiver::init(osuCrypto::u64,osuCrypto::PRNG &,osuCrypto::Socket &)': cannot convert argument 3 from 'T' to 'osuCrypto::Socket &'	libPSI	C:\Users\ceezous\Desktop\libPSI-private\libPSI\PSI\Kkrt\KkrtPsiReceiver.cpp	105

**Comment by ladnir** [comment]
You have the wrong version of libOTe. Did you install libOTe on your own?

**Comment by ladnir** [comment]
https://github.com/osu-crypto/libPSI/blob/2eb0514f66a0a0d8ce0ffcead73485886f21306f/thirdparty/getLibOTe.cmake#L4

LibOTe v1.6 should also work but the link above has the currently tested git commit.

**Comment by maplepicker** [comment]
> https://github.com/osu-crypto/libPSI/blob/2eb0514f66a0a0d8ce0ffcead73485886f21306f/thirdparty/getLibOTe.cmake#L4
> 
> LibOTe v1.6 should also work but the link above has the currently tested git commit.

Thanks for suggestion. Now I found that libOTe being configured properly, but it's relic that makes things complex. The information is: Build

  'C:/Program Files/CMake/bin/cmake.exe' '--build'
  'C:/Users/ceezous/Desktop/libPSI-private/thirdparty/libOTe/cryptoTools/thirdparty/relic/build/x64-Release'
  '--config' 'Release'

  CMake Error at cryptoTools/thirdparty/fetch.cmake:35 (message):

    Build failed (1).

**Comment by ladnir** [comment]
So libOTe is also going to pull in a bunch of things. Relic etc...

You will need to clone these manually as well. Or build the whole thing with internet and then move it off internet...
