### ISSUE TITLE
Confusion on implementions of KKRT-PSI

### ISSUE THREAD

**Issue by tiantianwangwang** [osu-crypto/libPSI#52]
I found that the implemention process is slightly different from the original paper DOI:[10.1145/2976749.2978381](https://doi.org/10.1145/2976749.2978381)
Here are my questions: 
1. When doing KKRT-PSI we first do an OPRF protocol. After the OPRF ,the sender will get keys(or called seeds)
![image](https://user-images.githubusercontent.com/60572346/205237827-1ce49142-8e2d-4a75-b3a7-e266a5ec9ad0.png)
 and the receiver will get F(k,d)
![image](https://user-images.githubusercontent.com/60572346/205237914-419c6a8f-3189-4627-803d-1938e6a29dfa.png)
I want to do something with these two items, but I couldn't find where they are in the code.

2. After OPRF, do keys, F(k,d) and the data that I inputted correspond in order? Or the output of keys, F(k,d) are disordered?

Any ideas help explaining?

**Comment by ladnir** [comment]
the ot code is here https://github.com/osu-crypto/libOTe/tree/master/libOTe/NChooseOne/Kkrt

here is where the receiver processes their values https://github.com/osu-crypto/libOTe/blob/master/libOTe/NChooseOne/Kkrt/KkrtNcoOtReceiver.cpp#L210
here is the sender https://github.com/osu-crypto/libOTe/blob/master/libOTe/NChooseOne/Kkrt/KkrtNcoOtSender.cpp#L193

**Comment by tiantianwangwang** [comment]
That's really helpful! Thank you.

But I have met a new problem: the sender need to rebuild F(k,a). //a is the input of the sender.
According to the paper, I find the formulation should be 
![image](https://user-images.githubusercontent.com/60572346/205483844-c3e58e49-6492-4be2-9e40-708968ab1cb8.png)
I think q matrix is here https://github.com/osu-crypto/libPSI/blob/2eb0514f66a0a0d8ce0ffcead73485886f21306f/libPSI/PSI/Kkrt/KkrtPsiSender.cpp#L374

s is here https://github.com/osu-crypto/libOTe/blob/b6e3a9d157cb3c2ea43815c105eb7b4cac292dda/libOTe/NChooseOne/Kkrt/KkrtNcoOtSender.cpp#L15

c is here https://github.com/osu-crypto/libOTe/blob/b6e3a9d157cb3c2ea43815c105eb7b4cac292dda/libOTe/NChooseOne/Kkrt/KkrtNcoOtSender.cpp#L79

Is it right?

**Comment by ladnir** [comment]
C(r) is the codeword https://github.com/osu-crypto/libOTe/blob/b6e3a9d157cb3c2ea43815c105eb7b4cac292dda/libOTe/NChooseOne/Kkrt/KkrtNcoOtSender.cpp#L206

that equation is computed here https://github.com/osu-crypto/libOTe/blob/b6e3a9d157cb3c2ea43815c105eb7b4cac292dda/libOTe/NChooseOne/Kkrt/KkrtNcoOtSender.cpp#L221

**Comment by tiantianwangwang** [comment]
Hi Iadnir! Thank you for your help.
I fixed this problem successfully, and now there is the last error: How the sender transmits the message to the receiver.

The sender wants to send the message to the receiver，
I tried to use std::array to generate a two-dimensional array
`std::array<std::array<block, 2>, mSenderSize>`
but it will result in an error.
![image](https://user-images.githubusercontent.com/60572346/206389413-b12065c8-039e-4b16-a91d-6fec41895cf2.png)

So I try to use std::vector, store the message in a vector and then use `chl.asyncSend((u8*)&v, v.size()*sizeof(block));` to send the vector,  and the receiver try to use `auto futest1 = chl0.asyncRecv((u8*)&v, v.size()*sizeof(block));` to get the message.
The error is like this
![image](https://user-images.githubusercontent.com/60572346/206391201-f51fb499-d347-4670-bccf-ca14d3df682d.png)

Any ideas help explaining?

**Comment by ladnir** [comment]
it basically tells you. The receive buffer does not have the same size as the send buffer. Either they are different sizes or maybe you aren't matching the correct send/receive pair.

**Comment by tiantianwangwang** [comment]
OK, I will test it

**Comment by tiantianwangwang** [comment]
Hello Iadnir, In kkrt protocol I met two problems here.

1. How to pass a std::vector data from sender to receiver. Which function can do this in this lib.

2. How to extend the output of OPRF,  such as now the output of OPRF is 128bit, and I need the output 256bit.

**Comment by ladnir** [comment]
How to send data? There are lots of examples in the code base... Either

`cp::sync_wait(socket.send(vec));`

Or

`MC_AWAIT(socket.send(vec));`

use the second if your in a coroutine and the first otherwise. Receive is the same but `.recv(...)`.

The vector must have some basic data type for its elements...

See the tutorial if tour confused https://github.com/Visa-Research/coproto/blob/main/frontend/cpp14Tutorial.cpp

You can expand the oprf output size by rehashing the 128 bit output to your desired size. Either use `RandomOracle ro(32); ro.Update(v); to.Finalize(out);` or `PRNG prng(v); out=prng.get();` to do this.  Where `v` is 128 bit and `out` is your 256 not output.

**Comment by tiantianwangwang** [comment]
That is really useful! Thanks.

Also is there any hash function in this library? LIke sha-256,md5...
can you give me some examples?

**Comment by ladnir** [comment]
`RandomOracle` is a  hash function. Its Blake2. Its at least as secure as sha-256.

Never use md5. Forget that it exists.

**Comment by tiantianwangwang** [comment]
Hello Iadnir, It's about the class blake2 and some problems.
![image](https://user-images.githubusercontent.com/60572346/209835673-c05f60c4-064a-48e7-9199-cc416b131fe9.png)
I try to use the blake2 to hash some std::string. There may be some mistake when using .Update() to input the std::string. Can you give me some examples?
And if I remove the code
            `hashone.Reset();`
            `const std::string &r1 = n; `
            `hashone.Update(&r1);`
            `hashone.Final((u8 *)&hashdata);`
The `Segmentation fault` will disappear,  this is so weird.

**Comment by ladnir** [comment]
Idk about the seg fault but certainly your hashing the string wrong. A std string is a pointer to memory and a size. So your currently hashing a pointer and size. Not the content of the string... Use Update(string.data(), string.size())

**Comment by tiantianwangwang** [comment]
yeah, your are right.

I fixed the problem about .update().
But the Segmentation fault is a more serious problem.
In the code below I used blake2 to process strings and set up four cout to find the code that went wrong.
 ```
while (std::getline(file, buffer))
        {
            std::string ID = buffer.substr(0,18);
            hashone.Update(ID.data(),ID.size());
            hashone.Final((u8 *)&hashdata);
            std::cout<<'1'<<std::endl;
            hashone.Reset();
            v_ID_hash.push_back(hashdata);
            std::cout<<'1'<<std::endl;
            buffer = buffer.substr(19); 
            std::string buffer1 = buffer.substr(0, 32);
            std::string buffer2 = buffer.substr(32);
            myBuffer[0] = block(std::stoll(buffer1.substr(0, 16), 0, 16), std::stoll(buffer1.substr(16), 0, 16));
            myBuffer[1] = block(std::stoll(buffer2.substr(0, 16), 0, 16), std::stoll(buffer2.substr(16), 0, 16));
            std::cout<<'1'<<std::endl;
            v_data.push_back(Aestest.ecbEncBlock(myBuffer[0]));
            std::cout<<'1'<<std::endl;
            v_data.push_back(Aestest.ecbEncBlock(myBuffer[1]));
        }
```
The Segmentation fault occurred in `v_data.push_back(Aestest.ecbEncBlock(myBuffer[0]));`, and it seems because of the `blake2`.
If I remove the code of it, the error will disappear.

**Comment by ladnir** [comment]
I'm not sure and not very motivated to debug your segfaults. My suggestion is to turn on asan. That will help you find where you are accessing bad memory.

Build libOTe with

python3 build.py -D ENABLE_ASAN=true

**Comment by tiantianwangwang** [comment]
Hello Iadnir, It's about how to change the type from block to std::string.
I try to use `block.data()`, apparently there's some error here.
![image](https://user-images.githubusercontent.com/60572346/210966899-667c7897-fbef-4bdd-85ef-51d41a4da9b8.png)
Can you give me some examples?

**Comment by ladnir** [comment]
Don't change the libPSI code. Take your chosen type and hash out into a block... Then call libPSI.

**Comment by tiantianwangwang** [comment]
Hello Iadnir, it's been a long time.
I recently encountered another problem in KKRT, in addition to the already completed OPRF how can the sender and receiver do another OPRF with NcoOT code? 
In fact I'm not quite sure how NcoOT  relates to OPRF. (What means NcoOT?)

**Comment by ladnir** [comment]
Nco ot is n choose one ot. Oprf is more like n choose t ot.

Nco ot: the library allows the sender to compute t ots. For the i'th ot, the sender gets a random key k_i. With this key the sender can evaluate a random function F_{k_i} (x) for _any_ x in {1,2,...,n}. In total, the sender can therefore compute t * n possible output values. 

For the i'th ot, the receiver is allowed to choose _exactly_ one value y_i in {1,2,...,n} and learn the random looking value z_i = F_{k_i} (y_i). So the receiver can only learn t outputs, with each being derived from a _different_ key. 

The receiver has no idea what the keys are. They can _not_ compute any other outputs... From this interaction, sender has no way of knowing what y_i values the receiver used. The sender can compute z_i = F_{k_i} (y_i) if they, _by some other means_, know to use y_i as an input.

Normal Oprf: oprf is very similar but there is only _one_ key, k. The sender knows the key and therefore can compute F_k(x) for _any_ x in {1,...,n}.

The other difference is the the receiver is allowed to choose t values, y_1,...,y_t and learn the values z_i=F_k(y_i) for each i in {1,...,t}.

Again, the receiver has know idea what the key is and the sender has no idea what y_i values were used.


KKRT is an Nco ot protocol, not a normal oprf protocol. The kkrt paper might use the oprf term but it's not exactly a oprf. In particular, kkrf uses the term bark-oprf to describe their construction which is the same thing as a Nco ot protocol.

I'm not sure if I understand your first question. If it's how do you allow the receiver to learn multiple outputs for a single key, k_i, then the answer is that you can not do this with kkrt. Kkrt specifically only works when the receiver is allowed to learn exactly one value z_i per key k_i held by the sender.

If you want multiple values per key, then you need a normal oprf. If this is the case I can give some pointers on what oprf to use.

**Comment by tiantianwangwang** [comment]
Get it, and I I would like to expand on Nco ot.
In the new protocol, for the i'th ot, the sender gets two random key k_i_1 and k_i_2. The sender can compute z_i_1 = F_{k_i_1} (y_i) and z_i_2 = F_{k_i_2} (y_i). In total, the sender can therefore compute 2t * n possible output values.
Do you have any idea?

**Comment by ladnir** [comment]
Do you want to make sure the receiver uses the same input for key k_i_1 and k_i_2?

**Comment by tiantianwangwang** [comment]
Yes, I'm sure.

**Comment by ladnir** [comment]
OK, you can do this. Generate t noc ots like normal. The sender gets key k_i for the ith ot. Define new keys k_i_j = (k_i, j). Then 

    F'_{k_i_j} (x) = H(F_{k_i} (x), j)

Where H is a hash function or similar. That is, if you want to use the "1" key you simply rehash the normal output F_{k_i} (x) with the value 1. For the 2 key you do the same but with value 2.

**Comment by tiantianwangwang** [comment]
Perfect, I will try it. Thank you very much!
