### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by didadida321** [osu-crypto/libPSI#56]
I run frontend.exe -kkrt -in t2.csv -csv -r 1 -out test.out -ip xxxx, I encountered the following error, 

network send error: Connection reset by peer
 at  /libPSI/thirdparty/libOTe/cryptoTools/cryptoTools/Network/Channel.cpp:871
Segmentation fault

what is the reason.Thank you very much.

**Comment by ladnir** [comment]
That's a tough one to answer... First it looks like the socket got closed by the other party (maybe they crashed first) and then the program crashed for some other reason
