### ISSUE TITLE
build issue on linux 

### ISSUE THREAD

**Issue by haochenuw** [osu-crypto/libPSI#7]
Got this error message when running `make`. I built the libOTe with the simplestOT enabled. 

/home/haoche/Documents/Libraries/libOTe/lib/liblibOTe.a(SimplestOT.cpp.o): In function `osuCrypto::SimplestOT::send(gsl::span<std::array<long long __vector(2), 2ul>, -1l>, osuCrypto::PRNG&, osuCrypto::Channel&)':
SimplestOT.cpp:(.text._ZN9osuCrypto10SimplestOT4sendEN3gsl4spanISt5arrayIDv2_xLm2EELln1EEERNS_4PRNGERNS_7ChannelE+0x6d): undefined reference to `sender_genS'
SimplestOT.cpp:(.text._ZN9osuCrypto10SimplestOT4sendEN3gsl4spanISt5arrayIDv2_xLm2EELln1EEERNS_4PRNGERNS_7ChannelE+0x17e): undefined reference to `sender_keygen'
/home/haoche/Documents/Libraries/libOTe/lib/liblibOTe.a(SimplestOT.cpp.o): In function `osuCrypto::SimplestOT::receive(osuCrypto::BitVector const&, gsl::span<long long __vector(2), -1l>, osuCrypto::PRNG&, osuCrypto::Channel&)':
SimplestOT.cpp:(.text._ZN9osuCrypto10SimplestOT7receiveERKNS_9BitVectorEN3gsl4spanIDv2_xLln1EEERNS_4PRNGERNS_7ChannelE+0x72): undefined reference to `receiver_procS'
SimplestOT.cpp:(.text._ZN9osuCrypto10SimplestOT7receiveERKNS_9BitVectorEN3gsl4spanIDv2_xLln1EEERNS_4PRNGERNS_7ChannelE+0x7a): undefined reference to `receiver_maketable'
SimplestOT.cpp:(.text._ZN9osuCrypto10SimplestOT7receiveERKNS_9BitVectorEN3gsl4spanIDv2_xLln1EEERNS_4PRNGERNS_7ChannelE+0x111): undefined reference to `receiver_rsgen'
SimplestOT.cpp:(.text._ZN9osuCrypto10SimplestOT7receiveERKNS_9BitVectorEN3gsl4spanIDv2_xLln1EEERNS_4PRNGERNS_7ChannelE+0x1e0): undefined reference to `receiver_keygen'

**Comment by ladnir** [comment]
ill look into this. It appears you are not linking the simplestOT library (included) that defines those. You can try and figure out why cmake is not building and or linking it?

**Comment by ladnir** [comment]
You need to turn on simplest OT in libPSI.

`cmake . -DENABLE_SIMPLESTOT=ON`
