### ISSUE TITLE
Segmatation fault when running -kkrt

### ISSUE THREAD

**Issue by haochenuw** [osu-crypto/libPSI#8]
```
haoche@Toshiba-Linux:~/Documents/Libraries/libPSI$ ./bin/frontend.exe -kkrt
protocol     n      threads      total(ms)    online(ms)     comm (MB)        bandwidth (Mbps)
------------------------------------------------------------------------------------------------
  kkrt     2561 1.000000            36             0              0.05        6.26, 4.64
Segmentation fault (core dumped)
```

I tried `-kkrt -r 0` and also it gives some errors...

**Comment by ladnir** [comment]
yeah there is some issue with the demo seg-faulting but the actual protocol works. You can see this by running the unit tests. `frontend.exe -u`. Ill look into the issue at some point.

**Comment by freelyyu** [comment]
I run `./bin/frontend.exe -rr17a -v -r 0` in one terminal, and `./bin/frontend.exe -rr17a -v -r 1` in other terminal. Running protocol RR17a outputs the correct intersection. but it occurs `Segmentation fault (core dumped)`  at last(After protocol RR17a is finished). Then I use gdb to find out reason.  I add a breakpoint at line 285 in main.cpp. it shows the following information, I am not familiar with the communication. I wonder know if there is a solution to fix it if I only run protocol RR17a .
![5FSL%RS0UXSMR93I4Q91U(D](https://user-images.githubusercontent.com/39991677/73250690-4b556480-41f2-11ea-8815-e27f988c328f.png)
![GEN474@%4%75%$1{AH0TZTF](https://user-images.githubusercontent.com/39991677/73250698-4ee8eb80-41f2-11ea-82a7-f2f5e02afa51.png)

**Comment by freelyyu** [comment]
![97 D)}7W4B2C~WKZ9WM`W71](https://user-images.githubusercontent.com/39991677/73255263-d5a1c680-41fa-11ea-9f72-35e16f3c427c.png)

**Comment by ladnir** [comment]
pushed a workaround. Works on my bix now.

**Comment by ladnir** [comment]
the lastest libOTe/cryptoTools fixes the root cause.
