### ISSUE TITLE
problem when building libPSI

### ISSUE THREAD

**Issue by freelyyu** [osu-crypto/libPSI#9]
I run cmake with `cmake . -DENABLE_MIRACL=ON -DENABLE_SIMPLESTOT=ON`， then I run `make`, but it occurs the error as is shown in the following picture.
![Uploading 18KK`)}Z97R]_1]HN8HEQKJ.png…]()

**Comment by freelyyu** [comment]
After building relic with old version, I run `cmake` and `make`, there occurs another problem
![63}`C}LAM$1YEFOKC4 YGJG](https://user-images.githubusercontent.com/39991677/72679172-a34fe500-3ae7-11ea-84b2-574c0781cf28.png)

**Comment by freelyyu** [comment]
I address the second problem by adding the header file `RandomOracle.h`, but it failed again when I cmake only with miracl on,  Here is part of the error.
[ERROR.txt](https://github.com/osu-crypto/libPSI/files/4082801/ERROR.txt)

**Comment by ladnir** [comment]
Pushed the RandomOracle.h fix.

FYI, you probably never need to have both MIRACL and Relic turned on.

This looks like you computed libOTe with different flags. Both libraries need to have the same flags for `ENABLE_MIRACL,ENABLE_RELIC,ENABLE_SIMPLESTOT`.

I just compiled libOTe and libPSI with `ENABLE_RELIC=ON` and the others set to off.
